datasource:
  dev:
    username: sa
    password: sa
    url: "jdbc:h2:./database"
  prod:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
ebean:
  migration:
    run: true