ebean:
  dbSchema: db
  migration:
    run: true

datasource:
  db:
    username: sa
    password: sa
    url: jdbc:h2:mem:myapp
  prod:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}